platform :ios, '6.0'
pod 'MagicalRecord', '~> 2.0.8'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta3'
pod 'NUI', '~>0.2.1'
pod 'RDActionSheet', '~>0.0.1'
pod 'AHAlertView', '~>0.0.2'
pod 'GVUserDefaults', '~>0.9.0'
